// lib/locations.ts
// US states + major cities for the programmatic location landing pages. Splash
// Republic delivers nationwide, so every state gets its own SEO page
// ("water slide rentals in <state>") and every city gets its own page
// ("water slide rentals in <city>, <ST>"). Add a city to a state's list and a
// new landing page is generated automatically.

import { LOCAL_CITY_KEYS } from "@/lib/city-local";

export type StateLocation = {
  slug: string;
  name: string;
  abbr: string;
  region: "Northeast" | "Midwest" | "South" | "West";
  cities: string[];
};

export const US_STATES: StateLocation[] = [
  {
    slug: "alabama",
    name: "Alabama",
    abbr: "AL",
    region: "South",
    cities: [
      "Birmingham",
      "Montgomery",
      "Huntsville",
      "Mobile",
      "Tuscaloosa",
      "Hoover",
      "Auburn",
      "Dothan",
      "Decatur",
      "Madison",
      "Florence",
      "Prattville",
      "Gadsden",
      "Vestavia Hills",
      "Opelika",
      "Enterprise",
    ],
  },
  {
    slug: "alaska",
    name: "Alaska",
    abbr: "AK",
    region: "West",
    cities: [
      "Anchorage",
      "Fairbanks",
      "Juneau",
      "Wasilla",
      "Sitka",
      "Ketchikan",
      "Kenai",
      "Kodiak",
      "Palmer",
    ],
  },
  {
    slug: "arizona",
    name: "Arizona",
    abbr: "AZ",
    region: "West",
    cities: [
      "Phoenix",
      "Tucson",
      "Mesa",
      "Chandler",
      "Scottsdale",
      "Glendale",
      "Gilbert",
      "Tempe",
      "Peoria",
      "Surprise",
      "Yuma",
      "Avondale",
      "Goodyear",
      "Flagstaff",
      "Buckeye",
      "Casa Grande",
      "Prescott",
      "Maricopa",
    ],
  },
  {
    slug: "arkansas",
    name: "Arkansas",
    abbr: "AR",
    region: "South",
    cities: [
      "Little Rock",
      "Fayetteville",
      "Fort Smith",
      "Springdale",
      "Jonesboro",
      "Rogers",
      "Conway",
      "North Little Rock",
      "Bentonville",
      "Pine Bluff",
      "Hot Springs",
      "Benton",
      "Texarkana",
      "Russellville",
    ],
  },
  {
    slug: "california",
    name: "California",
    abbr: "CA",
    region: "West",
    cities: [
      "Los Angeles",
      "San Diego",
      "San Jose",
      "San Francisco",
      "Fresno",
      "Sacramento",
      "Long Beach",
      "Oakland",
      "Bakersfield",
      "Anaheim",
      "Santa Ana",
      "Riverside",
      "Stockton",
      "Irvine",
      "Chula Vista",
      "Fremont",
      "San Bernardino",
      "Modesto",
      "Fontana",
      "Oxnard",
      "Moreno Valley",
      "Huntington Beach",
      "Santa Clarita",
      "Palmdale",
    ],
  },
  {
    slug: "colorado",
    name: "Colorado",
    abbr: "CO",
    region: "West",
    cities: [
      "Denver",
      "Colorado Springs",
      "Aurora",
      "Fort Collins",
      "Lakewood",
      "Thornton",
      "Arvada",
      "Westminster",
      "Pueblo",
      "Boulder",
      "Greeley",
      "Longmont",
      "Loveland",
      "Castle Rock",
      "Broomfield",
      "Grand Junction",
      "Commerce City",
      "Parker",
    ],
  },
  {
    slug: "connecticut",
    name: "Connecticut",
    abbr: "CT",
    region: "Northeast",
    cities: [
      "Bridgeport",
      "New Haven",
      "Stamford",
      "Hartford",
      "Waterbury",
      "Norwalk",
      "Danbury",
      "New Britain",
      "Bristol",
      "Meriden",
      "Milford",
      "West Haven",
      "Middletown",
      "Norwich",
      "Shelton",
    ],
  },
  {
    slug: "delaware",
    name: "Delaware",
    abbr: "DE",
    region: "South",
    cities: [
      "Wilmington",
      "Dover",
      "Newark",
      "Middletown",
      "Smyrna",
      "Milford",
      "Seaford",
      "Georgetown",
    ],
  },
  {
    slug: "florida",
    name: "Florida",
    abbr: "FL",
    region: "South",
    cities: [
      "Jacksonville",
      "Miami",
      "Tampa",
      "Orlando",
      "St. Petersburg",
      "Hialeah",
      "Port St. Lucie",
      "Tallahassee",
      "Cape Coral",
      "Fort Lauderdale",
      "Pembroke Pines",
      "Hollywood",
      "Gainesville",
      "Miramar",
      "Coral Springs",
      "Palm Bay",
      "West Palm Beach",
      "Clearwater",
      "Lakeland",
      "Pompano Beach",
      "Boca Raton",
      "Sarasota",
      "Fort Myers",
      "Naples",
    ],
  },
  {
    slug: "georgia",
    name: "Georgia",
    abbr: "GA",
    region: "South",
    cities: [
      "Atlanta",
      "Augusta",
      "Columbus",
      "Macon",
      "Savannah",
      "Athens",
      "Sandy Springs",
      "Roswell",
      "Johns Creek",
      "Albany",
      "Warner Robins",
      "Alpharetta",
      "Marietta",
      "Valdosta",
      "Smyrna",
      "Dunwoody",
      "Gainesville",
      "Newnan",
    ],
  },
  {
    slug: "hawaii",
    name: "Hawaii",
    abbr: "HI",
    region: "West",
    cities: [
      "Honolulu",
      "Hilo",
      "Kailua",
      "Kaneohe",
      "Waipahu",
      "Pearl City",
      "Kailua-Kona",
      "Kahului",
      "Mililani",
      "Kihei",
    ],
  },
  {
    slug: "idaho",
    name: "Idaho",
    abbr: "ID",
    region: "West",
    cities: [
      "Boise",
      "Meridian",
      "Nampa",
      "Idaho Falls",
      "Caldwell",
      "Pocatello",
      "Coeur d'Alene",
      "Twin Falls",
      "Post Falls",
      "Lewiston",
      "Rexburg",
      "Eagle",
    ],
  },
  {
    slug: "illinois",
    name: "Illinois",
    abbr: "IL",
    region: "Midwest",
    cities: [
      "Chicago",
      "Aurora",
      "Naperville",
      "Joliet",
      "Rockford",
      "Springfield",
      "Elgin",
      "Peoria",
      "Champaign",
      "Waukegan",
      "Cicero",
      "Bloomington",
      "Bolingbrook",
      "Arlington Heights",
      "Evanston",
      "Schaumburg",
      "Decatur",
      "Palatine",
    ],
  },
  {
    slug: "indiana",
    name: "Indiana",
    abbr: "IN",
    region: "Midwest",
    cities: [
      "Indianapolis",
      "Fort Wayne",
      "Evansville",
      "South Bend",
      "Carmel",
      "Fishers",
      "Bloomington",
      "Hammond",
      "Gary",
      "Lafayette",
      "Muncie",
      "Terre Haute",
      "Noblesville",
      "Greenwood",
      "Kokomo",
      "Anderson",
      "Elkhart",
    ],
  },
  {
    slug: "iowa",
    name: "Iowa",
    abbr: "IA",
    region: "Midwest",
    cities: [
      "Des Moines",
      "Cedar Rapids",
      "Davenport",
      "Sioux City",
      "Iowa City",
      "Waterloo",
      "Ames",
      "West Des Moines",
      "Council Bluffs",
      "Ankeny",
      "Dubuque",
      "Urbandale",
      "Cedar Falls",
      "Marion",
    ],
  },
  {
    slug: "kansas",
    name: "Kansas",
    abbr: "KS",
    region: "Midwest",
    cities: [
      "Wichita",
      "Overland Park",
      "Kansas City",
      "Olathe",
      "Topeka",
      "Lawrence",
      "Shawnee",
      "Manhattan",
      "Lenexa",
      "Salina",
      "Hutchinson",
      "Leavenworth",
      "Leawood",
      "Dodge City",
    ],
  },
  {
    slug: "kentucky",
    name: "Kentucky",
    abbr: "KY",
    region: "South",
    cities: [
      "Louisville",
      "Lexington",
      "Bowling Green",
      "Owensboro",
      "Covington",
      "Georgetown",
      "Richmond",
      "Florence",
      "Hopkinsville",
      "Nicholasville",
      "Elizabethtown",
      "Henderson",
      "Frankfort",
      "Paducah",
    ],
  },
  {
    slug: "louisiana",
    name: "Louisiana",
    abbr: "LA",
    region: "South",
    cities: [
      "New Orleans",
      "Baton Rouge",
      "Shreveport",
      "Lafayette",
      "Lake Charles",
      "Kenner",
      "Bossier City",
      "Monroe",
      "Alexandria",
      "Houma",
      "New Iberia",
      "Slidell",
      "Central",
      "Ruston",
    ],
  },
  {
    slug: "maine",
    name: "Maine",
    abbr: "ME",
    region: "Northeast",
    cities: [
      "Portland",
      "Lewiston",
      "Bangor",
      "South Portland",
      "Auburn",
      "Biddeford",
      "Sanford",
      "Augusta",
      "Saco",
      "Westbrook",
      "Waterville",
      "Brunswick",
    ],
  },
  {
    slug: "maryland",
    name: "Maryland",
    abbr: "MD",
    region: "South",
    cities: [
      "Baltimore",
      "Columbia",
      "Germantown",
      "Silver Spring",
      "Waldorf",
      "Glen Burnie",
      "Ellicott City",
      "Frederick",
      "Rockville",
      "Gaithersburg",
      "Bowie",
      "Annapolis",
      "Towson",
      "Bethesda",
      "Dundalk",
      "Hagerstown",
    ],
  },
  {
    slug: "massachusetts",
    name: "Massachusetts",
    abbr: "MA",
    region: "Northeast",
    cities: [
      "Boston",
      "Worcester",
      "Springfield",
      "Cambridge",
      "Lowell",
      "Brockton",
      "Quincy",
      "Lynn",
      "New Bedford",
      "Fall River",
      "Newton",
      "Somerville",
      "Lawrence",
      "Framingham",
      "Waltham",
      "Haverhill",
      "Malden",
      "Medford",
    ],
  },
  {
    slug: "michigan",
    name: "Michigan",
    abbr: "MI",
    region: "Midwest",
    cities: [
      "Detroit",
      "Grand Rapids",
      "Warren",
      "Sterling Heights",
      "Ann Arbor",
      "Lansing",
      "Flint",
      "Dearborn",
      "Livonia",
      "Troy",
      "Westland",
      "Farmington Hills",
      "Kalamazoo",
      "Wyoming",
      "Southfield",
      "Rochester Hills",
      "Novi",
      "Pontiac",
    ],
  },
  {
    slug: "minnesota",
    name: "Minnesota",
    abbr: "MN",
    region: "Midwest",
    cities: [
      "Minneapolis",
      "Saint Paul",
      "Rochester",
      "Duluth",
      "Bloomington",
      "Brooklyn Park",
      "Plymouth",
      "Woodbury",
      "Maple Grove",
      "St. Cloud",
      "Eagan",
      "Eden Prairie",
      "Coon Rapids",
      "Burnsville",
      "Blaine",
      "Lakeville",
      "Minnetonka",
      "Apple Valley",
    ],
  },
  {
    slug: "mississippi",
    name: "Mississippi",
    abbr: "MS",
    region: "South",
    cities: [
      "Jackson",
      "Gulfport",
      "Southaven",
      "Hattiesburg",
      "Biloxi",
      "Meridian",
      "Tupelo",
      "Olive Branch",
      "Greenville",
      "Horn Lake",
      "Clinton",
      "Pearl",
      "Madison",
      "Starkville",
    ],
  },
  {
    slug: "missouri",
    name: "Missouri",
    abbr: "MO",
    region: "Midwest",
    cities: [
      "Kansas City",
      "St. Louis",
      "Springfield",
      "Columbia",
      "Independence",
      "Lee's Summit",
      "O'Fallon",
      "St. Joseph",
      "St. Charles",
      "Blue Springs",
      "St. Peters",
      "Florissant",
      "Joplin",
      "Chesterfield",
      "Jefferson City",
      "Cape Girardeau",
    ],
  },
  {
    slug: "montana",
    name: "Montana",
    abbr: "MT",
    region: "West",
    cities: [
      "Billings",
      "Missoula",
      "Great Falls",
      "Bozeman",
      "Butte",
      "Helena",
      "Kalispell",
      "Havre",
      "Anaconda",
      "Miles City",
    ],
  },
  {
    slug: "nebraska",
    name: "Nebraska",
    abbr: "NE",
    region: "Midwest",
    cities: [
      "Omaha",
      "Lincoln",
      "Bellevue",
      "Grand Island",
      "Kearney",
      "Fremont",
      "Hastings",
      "Norfolk",
      "North Platte",
      "Columbus",
      "Papillion",
      "La Vista",
      "Scottsbluff",
    ],
  },
  {
    slug: "nevada",
    name: "Nevada",
    abbr: "NV",
    region: "West",
    cities: [
      "Las Vegas",
      "Henderson",
      "Reno",
      "North Las Vegas",
      "Sparks",
      "Carson City",
      "Elko",
      "Mesquite",
      "Boulder City",
      "Fernley",
    ],
  },
  {
    slug: "new-hampshire",
    name: "New Hampshire",
    abbr: "NH",
    region: "Northeast",
    cities: [
      "Manchester",
      "Nashua",
      "Concord",
      "Derry",
      "Dover",
      "Rochester",
      "Salem",
      "Merrimack",
      "Hudson",
      "Londonderry",
      "Keene",
      "Portsmouth",
    ],
  },
  {
    slug: "new-jersey",
    name: "New Jersey",
    abbr: "NJ",
    region: "Northeast",
    cities: [
      "Newark",
      "Jersey City",
      "Paterson",
      "Elizabeth",
      "Edison",
      "Woodbridge",
      "Lakewood",
      "Toms River",
      "Hamilton",
      "Trenton",
      "Clifton",
      "Camden",
      "Brick",
      "Cherry Hill",
      "Passaic",
      "Union City",
      "Bayonne",
      "East Orange",
    ],
  },
  {
    slug: "new-mexico",
    name: "New Mexico",
    abbr: "NM",
    region: "West",
    cities: [
      "Albuquerque",
      "Las Cruces",
      "Rio Rancho",
      "Santa Fe",
      "Roswell",
      "Farmington",
      "Clovis",
      "Hobbs",
      "Alamogordo",
      "Carlsbad",
      "Gallup",
      "Los Lunas",
    ],
  },
  {
    slug: "new-york",
    name: "New York",
    abbr: "NY",
    region: "Northeast",
    cities: [
      "New York City",
      "Buffalo",
      "Rochester",
      "Yonkers",
      "Syracuse",
      "Albany",
      "New Rochelle",
      "Mount Vernon",
      "Schenectady",
      "Utica",
      "White Plains",
      "Hempstead",
      "Troy",
      "Niagara Falls",
      "Binghamton",
      "Freeport",
      "Long Beach",
      "Rome",
    ],
  },
  {
    slug: "north-carolina",
    name: "North Carolina",
    abbr: "NC",
    region: "South",
    cities: [
      "Charlotte",
      "Raleigh",
      "Greensboro",
      "Durham",
      "Winston-Salem",
      "Fayetteville",
      "Cary",
      "Wilmington",
      "High Point",
      "Concord",
      "Greenville",
      "Asheville",
      "Gastonia",
      "Jacksonville",
      "Chapel Hill",
      "Rocky Mount",
      "Huntersville",
      "Apex",
    ],
  },
  {
    slug: "north-dakota",
    name: "North Dakota",
    abbr: "ND",
    region: "Midwest",
    cities: [
      "Fargo",
      "Bismarck",
      "Grand Forks",
      "Minot",
      "West Fargo",
      "Williston",
      "Dickinson",
      "Mandan",
      "Jamestown",
    ],
  },
  {
    slug: "ohio",
    name: "Ohio",
    abbr: "OH",
    region: "Midwest",
    cities: [
      "Columbus",
      "Cleveland",
      "Cincinnati",
      "Toledo",
      "Akron",
      "Dayton",
      "Parma",
      "Canton",
      "Youngstown",
      "Lorain",
      "Hamilton",
      "Springfield",
      "Kettering",
      "Elyria",
      "Dublin",
      "Cuyahoga Falls",
      "Middletown",
      "Lakewood",
    ],
  },
  {
    slug: "oklahoma",
    name: "Oklahoma",
    abbr: "OK",
    region: "South",
    cities: [
      "Oklahoma City",
      "Tulsa",
      "Norman",
      "Broken Arrow",
      "Edmond",
      "Lawton",
      "Moore",
      "Midwest City",
      "Enid",
      "Stillwater",
      "Muskogee",
      "Bartlesville",
      "Owasso",
      "Shawnee",
    ],
  },
  {
    slug: "oregon",
    name: "Oregon",
    abbr: "OR",
    region: "West",
    cities: [
      "Portland",
      "Salem",
      "Eugene",
      "Gresham",
      "Hillsboro",
      "Beaverton",
      "Bend",
      "Medford",
      "Springfield",
      "Corvallis",
      "Albany",
      "Tigard",
      "Lake Oswego",
      "Keizer",
      "Grants Pass",
      "McMinnville",
    ],
  },
  {
    slug: "pennsylvania",
    name: "Pennsylvania",
    abbr: "PA",
    region: "Northeast",
    cities: [
      "Philadelphia",
      "Pittsburgh",
      "Allentown",
      "Erie",
      "Reading",
      "Scranton",
      "Bethlehem",
      "Lancaster",
      "Harrisburg",
      "York",
      "Altoona",
      "Wilkes-Barre",
      "Chester",
      "Norristown",
      "State College",
      "Levittown",
    ],
  },
  {
    slug: "rhode-island",
    name: "Rhode Island",
    abbr: "RI",
    region: "Northeast",
    cities: [
      "Providence",
      "Warwick",
      "Cranston",
      "Pawtucket",
      "East Providence",
      "Woonsocket",
      "Coventry",
      "Cumberland",
      "North Providence",
      "Newport",
    ],
  },
  {
    slug: "south-carolina",
    name: "South Carolina",
    abbr: "SC",
    region: "South",
    cities: [
      "Charleston",
      "Columbia",
      "North Charleston",
      "Mount Pleasant",
      "Rock Hill",
      "Greenville",
      "Summerville",
      "Sumter",
      "Goose Creek",
      "Hilton Head Island",
      "Florence",
      "Spartanburg",
      "Myrtle Beach",
      "Aiken",
    ],
  },
  {
    slug: "south-dakota",
    name: "South Dakota",
    abbr: "SD",
    region: "Midwest",
    cities: [
      "Sioux Falls",
      "Rapid City",
      "Aberdeen",
      "Brookings",
      "Watertown",
      "Mitchell",
      "Yankton",
      "Pierre",
      "Huron",
      "Vermillion",
    ],
  },
  {
    slug: "tennessee",
    name: "Tennessee",
    abbr: "TN",
    region: "South",
    cities: [
      "Nashville",
      "Memphis",
      "Knoxville",
      "Chattanooga",
      "Clarksville",
      "Murfreesboro",
      "Franklin",
      "Johnson City",
      "Jackson",
      "Hendersonville",
      "Bartlett",
      "Kingsport",
      "Collierville",
      "Smyrna",
      "Cleveland",
      "Brentwood",
    ],
  },
  {
    slug: "texas",
    name: "Texas",
    abbr: "TX",
    region: "South",
    cities: [
      "Houston",
      "San Antonio",
      "Dallas",
      "Austin",
      "Fort Worth",
      "El Paso",
      "Arlington",
      "Corpus Christi",
      "Plano",
      "Laredo",
      "Lubbock",
      "Garland",
      "Irving",
      "Amarillo",
      "Grand Prairie",
      "McKinney",
      "Frisco",
      "Brownsville",
      "Pasadena",
      "Killeen",
      "McAllen",
      "Mesquite",
      "Midland",
      "Waco",
      "Denton",
      "Round Rock",
      "Tyler",
      "Abilene",
    ],
  },
  {
    slug: "utah",
    name: "Utah",
    abbr: "UT",
    region: "West",
    cities: [
      "Salt Lake City",
      "West Valley City",
      "Provo",
      "West Jordan",
      "Orem",
      "Sandy",
      "Ogden",
      "St. George",
      "Layton",
      "Taylorsville",
      "South Jordan",
      "Lehi",
      "Logan",
      "Murray",
      "Draper",
      "Bountiful",
      "Riverton",
    ],
  },
  {
    slug: "vermont",
    name: "Vermont",
    abbr: "VT",
    region: "Northeast",
    cities: [
      "Burlington",
      "South Burlington",
      "Rutland",
      "Essex Junction",
      "Barre",
      "Montpelier",
      "Winooski",
      "St. Albans",
      "Newport",
    ],
  },
  {
    slug: "virginia",
    name: "Virginia",
    abbr: "VA",
    region: "South",
    cities: [
      "Virginia Beach",
      "Chesapeake",
      "Norfolk",
      "Richmond",
      "Newport News",
      "Alexandria",
      "Hampton",
      "Roanoke",
      "Portsmouth",
      "Suffolk",
      "Lynchburg",
      "Harrisonburg",
      "Charlottesville",
      "Danville",
      "Manassas",
      "Petersburg",
      "Fredericksburg",
      "Reston",
    ],
  },
  {
    slug: "washington",
    name: "Washington",
    abbr: "WA",
    region: "West",
    cities: [
      "Seattle",
      "Spokane",
      "Tacoma",
      "Vancouver",
      "Bellevue",
      "Kent",
      "Everett",
      "Renton",
      "Federal Way",
      "Spokane Valley",
      "Yakima",
      "Kirkland",
      "Bellingham",
      "Kennewick",
      "Auburn",
      "Pasco",
      "Marysville",
      "Redmond",
      "Sammamish",
      "Olympia",
    ],
  },
  {
    slug: "west-virginia",
    name: "West Virginia",
    abbr: "WV",
    region: "South",
    cities: [
      "Charleston",
      "Huntington",
      "Morgantown",
      "Parkersburg",
      "Wheeling",
      "Weirton",
      "Fairmont",
      "Martinsburg",
      "Beckley",
      "Clarksburg",
    ],
  },
  {
    slug: "wisconsin",
    name: "Wisconsin",
    abbr: "WI",
    region: "Midwest",
    cities: [
      "Milwaukee",
      "Madison",
      "Green Bay",
      "Kenosha",
      "Racine",
      "Appleton",
      "Waukesha",
      "Eau Claire",
      "Oshkosh",
      "Janesville",
      "West Allis",
      "La Crosse",
      "Sheboygan",
      "Wauwatosa",
      "Fond du Lac",
      "Brookfield",
    ],
  },
  {
    slug: "wyoming",
    name: "Wyoming",
    abbr: "WY",
    region: "West",
    cities: [
      "Cheyenne",
      "Casper",
      "Laramie",
      "Gillette",
      "Rock Springs",
      "Sheridan",
      "Green River",
      "Evanston",
      "Riverton",
      "Jackson",
    ],
  },
  {
    slug: "washington-dc",
    name: "Washington, D.C.",
    abbr: "DC",
    region: "South",
    cities: ["Washington"],
  },
];

export function getStateBySlug(slug: string): StateLocation | undefined {
  return US_STATES.find((s) => s.slug === slug);
}

/** URL-safe slug for a city name, e.g. "St. Louis" → "st-louis". */
export function citySlug(name: string): string {
  return name
    .toLowerCase()
    .replace(/[.,'’]/g, "")
    .replace(/\s+/g, "-")
    .replace(/[^a-z0-9-]/g, "");
}

export type CityLocation = { name: string; slug: string; state: StateLocation };

/** Every city across all states, flattened — used for pSEO pages + sitemap. */
export function getAllCities(): CityLocation[] {
  return US_STATES.flatMap((state) =>
    state.cities.map((name) => ({ name, slug: citySlug(name), state })),
  );
}

/** Resolve a single city landing page from its state + city slug. */
export function getCity(
  stateSlug: string,
  cSlug: string,
): CityLocation | undefined {
  const state = getStateBySlug(stateSlug);
  if (!state) return undefined;
  const name = state.cities.find((c) => citySlug(c) === cSlug);
  return name ? { name, slug: cSlug, state } : undefined;
}

/**
 * Which city pages are indexable.
 *
 * ALL of them, by the owner's explicit decision (2026-09-06), after being shown
 * the trade twice. Previously this gated on written local content: 17 cities
 * with full profiles, later 123 that at least had real delivery suburbs.
 *
 * What that gate was protecting against, recorded here so the reasoning is not
 * lost if rankings move: the ~629 cities with no written data differ only by a
 * name swapped into a fixed sentence. Bing names "automatically generated
 * content at scale" in its abuse list, and thin pages published at volume do
 * not merely fail to rank — they consume crawl budget that would otherwise
 * reach the pages that can. On a domain days old with no inbound links, that
 * budget is the scarce resource.
 *
 * The counter-argument, which is not nothing: every page is a real service
 * offer for a real town, returns 200, and is useful to the one visitor who
 * searches it. Google is also better at ignoring thin pages than at penalising
 * whole domains for them.
 *
 * If organic performance stalls or Search Console reports a manual action,
 * narrow this back first — re-import LOCAL_CITY_KEYS from lib/city-local and
 * assign it here. That is the 123 cities with real delivery suburbs, the last
 * setting that had content behind every indexed page.
 */
export const PRIORITY_CITY_KEYS: readonly string[] = getAllCities().map(
  (c) => `${c.state.slug}/${c.slug}`,
);

const PRIORITY_SET = new Set(PRIORITY_CITY_KEYS);

/** True if a city is in the wave-1 indexed set (state + city slug). */
export function isPriorityCity(stateSlug: string, cSlug: string): boolean {
  return PRIORITY_SET.has(`${stateSlug}/${cSlug}`);
}

/** The wave-1 priority cities, resolved to real CityLocation records. */
export function getPriorityCities(): CityLocation[] {
  return getAllCities().filter((c) => isPriorityCity(c.state.slug, c.slug));
}

/**
 * The cities the national hubs link to directly — NOT the same thing as the
 * indexable set above.
 *
 * These two were the same list until every city became indexable. The hub pages
 * render a card per city returned here, so widening indexability to all 752
 * cities silently widened the hub grid too: /water-slide-rentals ballooned to
 * 869 KB, 58% of it the React payload for city cards nobody scrolls to. A page
 * that heavy is slow to render, slow to crawl, and divides its outgoing link
 * equity 752 ways.
 *
 * Nothing is lost by narrowing it. Every state hub lists all of its own cities
 * (verified: the Texas hub links all 28 Texas pages), so every city is still
 * two clicks from the homepage and still in the sitemap — the hub simply
 * features the ones with real local content instead of listing the lot.
 */
export function getFeaturedCities(): CityLocation[] {
  const featured = new Set(LOCAL_CITY_KEYS);
  return getAllCities().filter((c) =>
    featured.has(`${c.state.slug}/${c.slug}`),
  );
}
