/*
 * gen-indexing-urls.ts — regenerate indexing-urls.txt (the full list of public
 * URLs to submit to Google Search Console / Bing). Mirrors app/sitemap.ts:
 * static pages + states + every city + occasions + live product/rental/blog
 * slugs from the database. Every path is emitted in both /en and /fr.
 *
 * Run:  npm run gen:indexing-urls
 */
import { writeFileSync } from "node:fs";
import { PrismaPg } from "@prisma/adapter-pg";
import pkg from "@prisma/client";
import { US_STATES, getAllCities } from "../lib/locations.ts";
import { USE_CASES } from "../lib/use-cases.ts";

const { PrismaClient } = pkg;
const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter });

const BASE = "https://www.bigwaveslides.com";
const LOCALES = ["en", "fr"] as const;

const STATIC_PATHS = [
  "",
  "/about",
  "/services",
  "/shop",
  "/rent",
  "/blog",
  "/testimonials",
  "/contact",
  "/water-slide-rentals",
  "/water-slides-for",
  "/faq",
  "/privacy-policy",
  "/terms-of-service",
];

/** Expand one path into its /en and /fr absolute URLs. */
const urls = (path: string) => LOCALES.map((l) => `${BASE}/${l}${path}`);

async function main() {
  const [shop, rent, posts, blogCats, tags] = await Promise.all([
    prisma.product.findMany({
      where: { status: "ACTIVE", type: { in: ["SALE", "BOTH"] } },
      select: { slug: true },
      orderBy: { slug: "asc" },
    }),
    prisma.product.findMany({
      where: { status: "ACTIVE", type: { in: ["RENTAL", "BOTH"] } },
      select: { slug: true },
      orderBy: { slug: "asc" },
    }),
    prisma.blogPost.findMany({
      where: { status: "PUBLISHED" },
      select: { slug: true },
      orderBy: { slug: "asc" },
    }),
    prisma.blogCategory.findMany({
      select: { slug: true },
      orderBy: { slug: "asc" },
    }),
    prisma.tag.findMany({ select: { slug: true }, orderBy: { slug: "asc" } }),
  ]);

  const sections: { title: string; paths: string[] }[] = [
    { title: "MAIN PAGES", paths: STATIC_PATHS },
    {
      title: "STATES",
      paths: US_STATES.map((s) => `/water-slide-rentals/${s.slug}`),
    },
    {
      title: "CITIES",
      paths: getAllCities().map(
        (c) => `/water-slide-rentals/${c.state.slug}/${c.slug}`,
      ),
    },
    {
      title: "OCCASIONS",
      paths: USE_CASES.map((u) => `/water-slides-for/${u.slug}`),
    },
    { title: "SHOP PRODUCTS", paths: shop.map((p) => `/shop/${p.slug}`) },
    { title: "RENTALS", paths: rent.map((p) => `/rent/${p.slug}`) },
    { title: "BLOG POSTS", paths: posts.map((p) => `/blog/${p.slug}`) },
    {
      title: "BLOG CATEGORIES",
      paths: blogCats.map((c) => `/blog/category/${c.slug}`),
    },
    { title: "BLOG TAGS", paths: tags.map((t) => `/blog/tag/${t.slug}`) },
  ];

  const total =
    sections.reduce((n, s) => n + s.paths.length, 0) * LOCALES.length;

  const lines: string[] = [
    "# Big Wave Slides — URLs for Search Console / Bing indexing",
    `# Auto-generated by scripts/gen-indexing-urls.ts from the sitemap sources + DB.`,
    `# Total URLs: ${total} (English + French). Each page exists in both /en and /fr;`,
    "# the sitemap links them via hreflang, so submitting the sitemap once covers all.",
    "",
    "## SITEMAP  — submit this ONE link in GSC > Sitemaps and Bing > Sitemaps",
    `${BASE}/sitemap.xml`,
    "",
  ];

  for (const s of sections) {
    lines.push(`## ${s.title}  (${s.paths.length * LOCALES.length})`);
    for (const p of s.paths) for (const u of urls(p)) lines.push(u);
    lines.push("");
  }

  writeFileSync("indexing-urls.txt", lines.join("\n"));
  console.log(
    `Wrote indexing-urls.txt — ${total} URLs across ${sections.length} sections.`,
  );
  for (const s of sections)
    console.log(`  ${s.title}: ${s.paths.length} paths`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exitCode = 1;
  })
  .finally(() => prisma.$disconnect());
