/*
 * gen-indexing-urls.ts — regenerate indexing-urls.txt: ONLY the URLs we
 * actually want indexed, mirroring the trimmed app/sitemap.ts. That means:
 *   • bilingual (/en + /fr) for the fully-translated pages (core + products/blog)
 *   • English-only for the location + use-case pages (their /fr variants render
 *     English and are noindexed), and
 *   • only the wave-1 PRIORITY cities — the other city pages are noindexed until
 *     the domain earns authority, so they're deliberately excluded here.
 *
 * Run:  npm run gen:indexing-urls
 */
import { writeFileSync } from "node:fs";
import { PrismaPg } from "@prisma/adapter-pg";
import pkg from "@prisma/client";
import { US_STATES, getPriorityCities } from "../lib/locations";
import { USE_CASES } from "../lib/use-cases";

const { PrismaClient } = pkg;
const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter });

const BASE = "https://www.bigwaveslides.com";
const BOTH = ["en", "fr"] as const;
const EN = ["en"] as const;

// Fully-translated pages → indexed in both locales.
const BILINGUAL_STATIC = [
  "",
  "/about",
  "/services",
  "/shop",
  "/rent",
  "/blog",
  "/testimonials",
  "/contact",
  "/faq",
  "/privacy-policy",
  "/terms-of-service",
];
// English-only programmatic pages (their /fr twins are noindexed duplicates).
const EN_ONLY_STATIC = ["/water-slide-rentals", "/water-slides-for", "/answers"];

type Section = {
  title: string;
  paths: string[];
  locales: readonly ("en" | "fr")[];
};

async function main() {
  // Neon serverless can cold-start and time out the first query — warm the
  // connection with a few retries before firing the real (concurrent) queries.
  for (let i = 0; i < 8; i++) {
    try {
      await prisma.$queryRaw`SELECT 1`;
      break;
    } catch {
      await new Promise((r) => setTimeout(r, 2500));
    }
  }

  // Sequential (not Promise.all): a cold Neon connection can't reliably service
  // several concurrent queries — run them one at a time.
  const shop = await prisma.product.findMany({
    where: { status: "ACTIVE", type: { in: ["SALE", "BOTH"] } },
    select: { slug: true },
    orderBy: { slug: "asc" },
  });
  const rent = await prisma.product.findMany({
    where: { status: "ACTIVE", type: { in: ["RENTAL", "BOTH"] } },
    select: { slug: true },
    orderBy: { slug: "asc" },
  });
  const posts = await prisma.blogPost.findMany({
    where: { status: "PUBLISHED" },
    select: { slug: true },
    orderBy: { slug: "asc" },
  });
  const blogCats = await prisma.blogCategory.findMany({
    select: { slug: true },
    orderBy: { slug: "asc" },
  });
  const tags = await prisma.tag.findMany({
    select: { slug: true },
    orderBy: { slug: "asc" },
  });

  const sections: Section[] = [
    { title: "MAIN PAGES (en + fr)", paths: BILINGUAL_STATIC, locales: BOTH },
    { title: "HUBS & ANSWERS (en)", paths: EN_ONLY_STATIC, locales: EN },
    {
      title: "STATES (en)",
      paths: US_STATES.map((s) => `/water-slide-rentals/${s.slug}`),
      locales: EN,
    },
    {
      title: "PRIORITY CITIES (en)",
      paths: getPriorityCities().map(
        (c) => `/water-slide-rentals/${c.state.slug}/${c.slug}`,
      ),
      locales: EN,
    },
    {
      title: "USE-CASE PAGES (en)",
      paths: USE_CASES.map((u) => `/water-slides-for/${u.slug}`),
      locales: EN,
    },
    {
      title: "SHOP PRODUCTS (en + fr)",
      paths: shop.map((p) => `/shop/${p.slug}`),
      locales: BOTH,
    },
    {
      title: "RENTALS (en + fr)",
      paths: rent.map((p) => `/rent/${p.slug}`),
      locales: BOTH,
    },
    {
      title: "BLOG POSTS (en + fr)",
      paths: posts.map((p) => `/blog/${p.slug}`),
      locales: BOTH,
    },
    {
      title: "BLOG CATEGORIES (en + fr)",
      paths: blogCats.map((c) => `/blog/category/${c.slug}`),
      locales: BOTH,
    },
    {
      title: "BLOG TAGS (en + fr)",
      paths: tags.map((t) => `/blog/tag/${t.slug}`),
      locales: BOTH,
    },
  ];

  // Split output into an ENGLISH block (every section) and a FRENCH block (only
  // the bilingual sections) so the English pages can be submitted for indexing
  // first — the priority on a young domain.
  const baseName = (t: string) => t.replace(/\s*\([^)]*\)\s*$/, "");
  const frSections = sections.filter((s) => s.locales.includes("fr"));
  const enCount = sections.reduce((n, s) => n + s.paths.length, 0);
  const frCount = frSections.reduce((n, s) => n + s.paths.length, 0);
  const total = enCount + frCount;

  const lines: string[] = [
    "# Big Wave Slides — URLs to submit for indexing (Google Search Console / Bing)",
    "# Auto-generated by scripts/gen-indexing-urls.ts — mirrors the TRIMMED sitemap.",
    `# Total indexable URLs: ${total} (${enCount} English, ${frCount} French).`,
    "# English and French are split into two blocks — submit the ENGLISH block FIRST.",
    "# Only pages we WANT indexed are listed: priority cities only; location/use-case",
    "# pages are English-only (their /fr twins are noindexed). Do NOT submit others.",
    "",
    "## FASTEST PATH — submit this ONE sitemap in GSC > Sitemaps and Bing > Sitemaps",
    `${BASE}/sitemap.xml`,
    "",
    "## PRIORITY: index the ENGLISH block first, then the FRENCH block.",
    "##   Within English: MAIN PAGES > STATES > PRIORITY CITIES > USE-CASE > the rest",
    "",
    `################  ENGLISH — INDEX THESE FIRST  (${enCount})  ################`,
    "",
  ];

  for (const s of sections) {
    lines.push(`## ${baseName(s.title)} (en)  (${s.paths.length})`);
    for (const p of s.paths) lines.push(`${BASE}/en${p}`);
    lines.push("");
  }

  lines.push(
    `################  FRENCH — INDEX AFTER ENGLISH  (${frCount})  ################`,
    "",
  );
  for (const s of frSections) {
    lines.push(`## ${baseName(s.title)} (fr)  (${s.paths.length})`);
    for (const p of s.paths) lines.push(`${BASE}/fr${p}`);
    lines.push("");
  }

  writeFileSync("indexing-urls.txt", lines.join("\n"));
  console.log(
    `Wrote indexing-urls.txt — ${total} URLs (${enCount} English, ${frCount} French).`,
  );
}

main()
  .catch((e) => {
    console.error(e);
    process.exitCode = 1;
  })
  .finally(() => prisma.$disconnect());
