/*
 * gen-indexing-urls.ts — regenerate indexing-urls.txt: ONLY the URLs we
 * actually want indexed, mirroring app/sitemap.ts.
 *
 * The site is English-only (see i18n/routing.ts); the old /fr URLs 301 to /en
 * and must never be submitted — you only ever submit final, canonical, 200-OK
 * URLs. Only the wave-1 PRIORITY cities are listed: the other city pages are
 * deliberately noindexed until the domain earns authority.
 *
 * Run:  npm run gen:indexing-urls
 */
import { writeFileSync } from "node:fs";
import { PrismaPg } from "@prisma/adapter-pg";
import pkg from "@prisma/client";
import { US_STATES, getPriorityCities } from "../lib/locations";
import { USE_CASES } from "../lib/use-cases";

const { PrismaClient } = pkg;
const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter });

const BASE = "https://www.splashrep.com";
const EN = ["en"] as const;

const CORE_STATIC = [
  "",
  "/about",
  "/services",
  "/shop",
  "/rent",
  "/blog",
  "/testimonials",
  "/contact",
  "/faq",
  "/privacy-policy",
  "/terms-of-service",
];
const HUB_STATIC = [
  "/water-slide-rentals",
  "/bounce-house-rentals",
  "/water-slides-for",
  "/answers",
];

type Section = {
  title: string;
  paths: string[];
  locales: readonly "en"[];
};

async function main() {
  // Neon serverless can cold-start and time out the first query — warm the
  // connection with a few retries before firing the real (concurrent) queries.
  for (let i = 0; i < 8; i++) {
    try {
      await prisma.$queryRaw`SELECT 1`;
      break;
    } catch {
      await new Promise((r) => setTimeout(r, 2500));
    }
  }

  // Sequential (not Promise.all): a cold Neon connection can't reliably service
  // several concurrent queries — run them one at a time.
  const shop = await prisma.product.findMany({
    where: { status: "ACTIVE", type: { in: ["SALE", "BOTH"] } },
    select: { slug: true },
    orderBy: { slug: "asc" },
  });
  const rent = await prisma.product.findMany({
    where: { status: "ACTIVE", type: { in: ["RENTAL", "BOTH"] } },
    select: { slug: true },
    orderBy: { slug: "asc" },
  });
  const posts = await prisma.blogPost.findMany({
    where: { status: "PUBLISHED" },
    select: { slug: true },
    orderBy: { slug: "asc" },
  });
  const blogCats = await prisma.blogCategory.findMany({
    select: { slug: true },
    orderBy: { slug: "asc" },
  });
  const tags = await prisma.tag.findMany({
    select: { slug: true },
    orderBy: { slug: "asc" },
  });

  const sections: Section[] = [
    { title: "MAIN PAGES", paths: CORE_STATIC, locales: EN },
    { title: "HUBS & ANSWERS", paths: HUB_STATIC, locales: EN },
    {
      title: "STATES",
      paths: US_STATES.map((s) => `/water-slide-rentals/${s.slug}`),
      locales: EN,
    },
    {
      title: "PRIORITY CITIES",
      paths: getPriorityCities().map(
        (c) => `/water-slide-rentals/${c.state.slug}/${c.slug}`,
      ),
      locales: EN,
    },
    {
      title: "BOUNCE HOUSE STATES",
      paths: US_STATES.map((s) => `/bounce-house-rentals/${s.slug}`),
      locales: EN,
    },
    {
      title: "USE-CASE PAGES",
      paths: USE_CASES.map((u) => `/water-slides-for/${u.slug}`),
      locales: EN,
    },
    {
      title: "SHOP PRODUCTS",
      paths: shop.map((p) => `/shop/${p.slug}`),
      locales: EN,
    },
    {
      title: "RENTALS",
      paths: rent.map((p) => `/rent/${p.slug}`),
      locales: EN,
    },
    {
      title: "BLOG POSTS",
      paths: posts.map((p) => `/blog/${p.slug}`),
      locales: EN,
    },
    {
      title: "BLOG CATEGORIES",
      paths: blogCats.map((c) => `/blog/category/${c.slug}`),
      locales: EN,
    },
    {
      title: "BLOG TAGS",
      paths: tags.map((t) => `/blog/tag/${t.slug}`),
      locales: EN,
    },
  ];

  const baseName = (t: string) => t.replace(/\s*\([^)]*\)\s*$/, "");
  const total = sections.reduce((n, s) => n + s.paths.length, 0);

  const lines: string[] = [
    "# Splash Republic — URLs to submit for indexing (Google Search Console / Bing)",
    "# Auto-generated by scripts/gen-indexing-urls.ts — mirrors app/sitemap.ts.",
    `# Total indexable URLs: ${total}. English (en-US) only — the site has one language.`,
    "# The retired /fr URLs are NOT listed: they 301 to /en, and submitting a",
    "# redirect wastes crawl budget (Search Console reports it as 'Page with redirect').",
    "# Only pages we WANT indexed are here: priority cities only. Do NOT submit others.",
    "",
    "## FASTEST PATH — submit this ONE sitemap in GSC > Sitemaps and Bing > Sitemaps",
    `${BASE}/sitemap.xml`,
    "",
    "## PRIORITY ORDER: MAIN PAGES > HUBS > STATES > PRIORITY CITIES > USE-CASE > the rest",
    "",
    `################  ${total} URLs  ################`,
    "",
  ];

  for (const s of sections) {
    lines.push(`## ${baseName(s.title)}  (${s.paths.length})`);
    for (const p of s.paths) lines.push(`${BASE}/en${p}`);
    lines.push("");
  }

  writeFileSync("indexing-urls.txt", lines.join("\n"));
  console.log(`Wrote indexing-urls.txt — ${total} URLs (English only).`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exitCode = 1;
  })
  .finally(() => prisma.$disconnect());
